# bundle exec jekyll serve --host=0.0.0.0

title: MycilaTaskMonitor
description: Arduino / ESP32 library to monitor task priority and stack high watermark
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
